apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: harness-service-to-catalog
spec:
  type: url
  targets:
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/Harness_Platform_Management/_domain.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/Harness_Platform_Management/Image_Factory/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/Harness_Platform_Management/Delegate_Management/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/Harness_Platform_Management/Solutions_Factory/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/_domain.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/code_iacm_ccm_connectors/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ccm_code_iacm_connectors/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ci/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/dev/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ansible/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/idp/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ff_demo/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/ansible.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/ff_relay_proxy.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/metrics_server.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/delegate.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/auto_stopping_lab/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/ffrelayproxyhelm.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/guestbook.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/gitgeneratorfilesdiscovery.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/redis.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/media.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/frigate.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/whoami.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/gitness.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/ff_relay_proxy.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/harness_ccm_k8s_auto.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/ssh.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/serverless.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/nginx.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/delegate.yaml  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/_domain.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/code_iacm_ccm_connectors/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ccm_code_iacm_connectors/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ci/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/dev/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ansible/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/idp/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/ff_demo/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/ansible.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/default/ff_relay_proxy.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/metrics_server.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/iacm/delegate.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/auto_stopping_lab/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/ffrelayproxyhelm.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/guestbook.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/gitgeneratorfilesdiscovery.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/redis.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/media.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/frigate.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/whoami.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/gitness.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/ff_relay_proxy.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/home_lab/harness_ccm_k8s_auto.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/_system.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/ssh.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/serverless.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/nginx.yaml
  - https://github.com/rssnyder/idp-service-catalog/idp-service-catalog/default/Default_Project_1662659562703/delegate.yaml
