apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Default_Project_1662659562703
  description: 
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/wlgELJ0TTre5aZhzpt8gVA/cd/orgs/default/projects/Default_Project_1662659562703
spec:
  owner: admins
  domain: default