apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible
  description: 
  namespace: default
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/wlgELJ0TTre5aZhzpt8gVA/cd/orgs/default/projects/default
    harness.io/services: >
      ansible:
      https://app.harness.io/ng/account/wlgELJ0TTre5aZhzpt8gVA/cd/orgs/default/projects/default/services/ansible
spec:
  type: service
  owner: admins
  system: default
  lifecycle: experimental